state_dim: 2
action_num: 8
group_num: 3
pref_data_num: 300
batch_size: 300
dpo_num_iters: 20000
step_size: 0.1
reg_coef: 1.0
exp_step_size: 0.01
eval_metric: 'argmax'
param_limit: 5
chi: 1
C: 0

reward_param: [[1.0,3.0,1.0,3.0],[3.0,1.0,3.0,1.0],[1.5,2.5,1.5,2.5]]
weights: [1,1,0.4]
val_weights: [1,1,1]
test_weights: [1,1,1]

wandb:
  project: "noisy_exp"
  group: 'group_exp'

feature_types:
  - "swapped"

noise_levels:
  - 1.0
  - 0.9
  - 0.8
  - 0.7
  - 0.6
  - 0.5
  - 0.4
  - 0.3

seeds:
  - 2021
  - 2022
  - 2023
  - 2024
  - 2025
  - 2026
  - 2027
  - 2028
  - 2029
  - 2030
